### ISSUE TITLE
Horizon helm chart installation fails on non-OpenShift clusters.

### ISSUE THREAD

**Issue by amilstead** [OpenNMS/helm-charts#57]
## Describe the bug

Helm chart installation fails on non-OpenShift clusters.

## To Reproduce

Use the quickstart instructions here with a non-OpenShift kubernetes cluster: https://opennms.github.io/helm-charts/horizon/, i.e.

```
helm repo add opennms https://opennms.github.io/helm-charts

helm install monms opennms/horizon --set domain=domain1.com  --create-namespace
```

The result is a container spec validation error for the core statefulset container: 
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(StatefulSet.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext, ValidationError(StatefulSet.spec.template.spec.initContainers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext]`

## Expected behavior

Helm install succeeds, rendered "NOTES.txt" is printed to console.

## Desktop
 - OS: Ubuntu 22.04
 - Kubernetes distro: [RKE2](https://docs.rke2.io/) v1.26
 - Chart Version: opennms/horizon @ 1.1.10

## Additional context

I would like to evaluate OpenNMS for usage in my network, I am using RKE2 as the kubernetes distro of choice.

**Comment by amilstead** [comment]
> Thank you for reporting this bug.
> 
> Would it be possible for you to test deploying the chart from the following branch https://github.com/OpenNMS/helm-charts/tree/mem/NMS-16365 ?

Hi there, thanks!

That seems to get me past the initial installation, however the installation hangs as it seems to expect an external postgres database by default.

When I get some actual time I may try deploying said database. That said, it would be nice if this were something the helm chart could support in terms of a deployment to avoid additional extra resource management overhead.

**Comment by mershad-manesh** [comment]
This issue is resolved in the latest release
